import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'collumn',
  },
  navbar: {
    width: '100%',
    height: '25%',
    backgroundColor: '#462a71',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  navbarIni:{
    width: '100%',
    height: '20%',
    justifyContent: 'center',
    display:'flex',
    flexDirection:'row',
    top:'10%',
    gap:'20%',
  },
  navbarBox: {
    width: '90%',
    height: '60%',
    backgroundColor: '#462a71', 
    top: '20%',
    borderRadius: 10,
    borderWidth: 6,
    borderColor: '#fff',
    paddingHorizontal: 15,
    justifyContent: 'center',
  },
  flatList: {
    width: '100%',
    height: '80%',
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  flatListBox: {
    width: '95%',
    height: '100%',
    backgroundColor: '#fff',
    display:'flex',
    flexDirection:'column',
    marginTop:20,
  },
    cardBox:{
    width: '90%',
    height:'100%',
    maxHeight:'100%',
    marginHorizontal:'5%',
    marginVertical:10,
  }, 
  card:{
    borderWidth:3,
    borderColor:'#462a71',
    padding:10,
    borderRadius:10,
  }, 
  cardLinha: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 5,
  },
  cardTextDesc:{
    fontSize:25,
  },
  cardTextValor:{
    fontSize:25,
    
  },
  cardText:{
    fontSize:15,
  },
  plus: {
    width: 60,
    height: 60,
    position: 'relative',
    marginBottom: 20,
  },
  plusA: {
    width: 60,
    height: 60,
    backgroundColor: '#fff',
    borderRadius: 50,
    position: 'absolute',
    top: '75%',
    left: '79%',
  },
  plusB: {
    width: 60,
    height: 60,
    backgroundColor: '#fff',
    borderRadius: 50,
    position: 'absolute',
    top: '83%',
    left: '79%',
  },
  modalA: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(94, 93, 93, 0.8)',
  },
  modalBox: {
    width: '80%',
    height: '60%',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 30,
    borderWidth: 4,
    borderColor: '#432374',
  },
  modalBoxDelete:{
    width: '80%',
    height: '30%',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingTop:20,
    borderRadius: 30,
    borderWidth: 4,
    borderColor: '#432374',
  },
  modalBoxA: {
    top: '10%',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',

  },
  titulo: {
    fontSize: 20,
  },
  TArea: {
    width: '95%',
    height: '80%',
    borderColor: '#432374',
    justifyContent: 'center',
    alignItems: 'center',
  },
  linha: {
    width: '95%',
    height: '20%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap:15,
    marginBottom:30,
  },
  input: {
    fontSize:20,
    textAlign:'center',
    width: '100%',
    height: '80%',
    color:'#000',
    borderWidth: 3,
    borderRadius:10,
    borderColor: 'rgba(67, 35, 116, 0.7)',
  },
  inputA: {
    fontSize:20,
    color:'#000',
    textAlign:'center',
    width: '50%',
    height: '80%',
    borderWidth: 3,
    borderRadius:10,
    borderColor: 'rgba(67, 35, 116, 0.7)',
    
  },
});
