import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'collumn',
  },
  navbar: {
    width: '100%',
    height: '25%',
    backgroundColor: '#00d14d',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  navbarIni:{
    width: '100%',
    height: '20%',
    justifyContent: 'center',
    display:'flex',
    flexDirection:'row',
    top:'10%',
    gap:'20%',
  },
  navbarBox: {
    width: '90%',
    height: '60%',
    backgroundColor: '#00d14d', 
    top: '20%',
    borderRadius: 10,
    borderWidth: 6,
    borderColor: 'rgb(0, 0, 0)',
    paddingHorizontal: 15,
    justifyContent: 'center',
    display:'flex',
    flexDirection:'column',
  },
  flatList: {
    width: '100%',
    height: '80%',
    backgroundColor: 'rgb(0, 0, 0)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  flatListBox: {
    width: '95%',
    height: '95%',
    backgroundColor: 'rgb(14, 14, 14)',
    display:'flex',
    flexDirection:'column',
  },
    cardBox:{
    width: '90%',
    height: 100,
    maxHeight:'100%',
    marginHorizontal:'5%',
    marginVertical:10,
  }, 
  card:{
    borderWidth:3,
    backgroundColor: 'rgba(37, 37, 37, 0.72)',
    borderColor:'rgba(124, 124, 124, 0.69)',
    padding:10,
    borderRadius:10,
  }, 
  cardLinha: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 5,
  },
  cardTextDesc:{
    fontSize:25,
    color:'#fff',
  },
  cardTextValor:{
    fontSize:25,
    
  },
  cardText:{
    fontSize:15,
    color:'#fff',
  },
  plus: {
    width: 60,
    height: 60,
    position: 'relative',
    marginBottom: 20,
  },
  plusA: {
    width: 60,
    height: 60,
    backgroundColor: '#fff',
    borderRadius: 50,
    position: 'absolute',
    top: '75%',
    left: '79%',
  },
  plusB: {
    width: 60,
    height: 60,
    backgroundColor: '#fff',
    borderRadius: 50,
    position: 'absolute',
    top: '83%',
    left: '79%',
  },
  modalA: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(94, 93, 93, 0.8)',
  },
  modalBox: {
    zIndex:3000000,
    width: '80%',
    height: 470,
    alignItems: 'center',
    backgroundColor: 'rgb(37, 37, 37)',
    borderRadius: 30,
    borderWidth: 4,
    borderColor: 'rgba(94, 93, 93, 0.8)',
        justifyContent:'center',
  },
  modalBoxP: {
    zIndex:3000000,
    width: '80%',
    height: 200,
    alignItems: 'center',
    justifyContent:'center',
    backgroundColor: 'rgb(37, 37, 37)',
    borderRadius: 30,
    borderWidth: 4,
    borderColor: 'rgba(94, 93, 93, 0.8)',
  },
  modalBoxDelete:{
    width: '80%',
    height: '30%',
    alignItems: 'center',
    backgroundColor: 'rgb(37, 37, 37)',
    paddingTop:20,
    borderRadius: 30,
    borderWidth: 4,
    borderColor: 'rgba(94, 93, 93, 0.8)',
  },
  modalBoxA: {
    top: '10%',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',

  },
  titulo: {
    fontSize: 30,
    color:'#fff',
    textAlign:'center',
  },
  TArea: {
    width: '95%',
    height: '80%',
    borderColor: '#00d14d',
    justifyContent: 'center',
    alignItems: 'center',
  },
  linha: {
    width: '95%',
    height: '20%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap:15,
    marginBottom:30,
  },
  input: {
    fontSize:20,
    textAlign:'center',
    width: '90%',
    height: '95%',
    color:'#000',
    borderWidth: 3,
    borderRadius:10,
    borderColor: 'rgba(94, 93, 93, 0.8)',
    backgroundColor:'rgb(231, 229, 229)',
  },
  inputA: {
    fontSize:20,
    color:'#000',
    textAlign:'center',
    width: '45%',
    height: '95%',
    borderWidth: 3,
    borderRadius:10,
    borderColor: 'rgba(94, 93, 93, 0.8)',
    backgroundColor:'rgb(231, 229, 229)',
  },
});
