import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'collun',
  },
  navbar: {
    width: '100%',
    height: '20%',
    backgroundColor: '#462a71',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  navbarBox: {
    width: '90%',
    height: '90%',
    backgroundColor: '#fff',
    top: '20%',
    borderRadius: 10,
    borderWidth: 3,
  },
  flatList: {
    width: '100%',
    height: '80%',
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  flatListBox: {
    width: '95%',
    height: '95%',
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  plus: {
    width: 60,
    height: 60,
    position: 'relative',
    marginBottom: 20,
  },
  plusA: {
    width: 60,
    height: 60,
    backgroundColor: '#fff',
    borderRadius: 50,
    position: 'absolute',
    top: '75%',
    left: '79%',
  },
  plusB: {
    width: 60,
    height: 60,
    backgroundColor: '#fff',
    borderRadius: 50,
    position: 'absolute',
    top: '83%',
    left: '79%',
  },
  modalA: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(94, 93, 93, 0.8)',
  },
  modalBox: {
    width: '80%',
    height: '60%',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 30,
    borderWidth: 4,
    borderColor: '#432374',
  },
  modalBoxA: {
    top: '10%',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',

  },
  titulo: {
    fontSize: 20,
  },
  TArea: {
    width: '95%',
    height: '80%',
    borderColor: '#432374',
    justifyContent: 'center',
    alignItems: 'center',
  },
  linha: {
    width: '95%',
    height: '20%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap:15,
    marginBottom:30,
  },
  input: {
    fontSize:20,
    textAlign:'center',
    width: '100%',
    height: '80%',
    color:'#000',
    borderWidth: 3,
    borderRadius:10,
    borderColor: 'rgba(67, 35, 116, 0.7)',
  },
  inputA: {
    fontSize:20,
    color:'#000',
    textAlign:'center',
    width: '50%',
    height: '80%',
    borderWidth: 3,
    borderRadius:10,
    borderColor: 'rgba(67, 35, 116, 0.7)',
    
  },
});
